config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'like/new'
  root 'users#index'
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :new, :create, :show] do 
      resources :comments, only: [:new, :create] 
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comment_counts

  private

  def update_comment_counts
    post = Post.find(post_id)
    post.commentscounter = Comment.where(post_id: post.id).count
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_like_counts

  private

  def update_like_counts
    post = Post.find(post_id)
    post.likescounter = Like.where(post_id: post.id).count
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments

  def recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  def post_count=(count)
    self.postscounter = count
  end

  after_save :update_post_counts

  private

  def update_post_counts
    user = User.find(user_id)
    user.postscounter = Post.where(user_id: user.id).count
    user.save
  end

  validates :title, presence: true, Length: { maximum: 250 }

  validates :commentscounter, :likescounter, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
end

app/models/user.rb
# rubocop:disable all
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :email, uniqueness: true
  validates :postscounter, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :name, :bio, :photo)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(
      text: params[:text],
      post_id: params[:post_id]
    )
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      flash.now[:alert] = 'Comment was not created.'
      render 'posts/show'
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(
      user_id: current_user.id,
      post_id: params[:post_id]
    )
    if @like.save
      flash[:notice] = 'Like was successfully created.'
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      flash.now[:alert] = 'Like was not created.'
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts, :comments, :likes).find_by_id(params[:user_id])
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = @post.recent_comments
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
      else
        format.html { render :new }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class='comment-form'>
<h1>Add a new comment</h1>
<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>

<div>
<li>
  <%= form.label :title %>
</li>
<li>
  <%= form.text_field :title %>
</li>

</div>
<div>
<li>
<%= form.label :text %>
</li>
<li>
<%= form.text_field :text %>
</li>
</div>

<%= form.submit "Add a comment" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section id='user-container'>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<img src="<%= @user.photo %>" alt="image">
<h1><%= @user.name%></h1>
</section>
<p id='user-bio'><%= @user.bio %></>
<div class='post-container'>
<p>I am gonna get a job in may</p>
<h1>Number of Posts:<%= @user.postscounter %></h1>
<% @user.posts.each_with_index do |post,index| %>
<li>
<p>Post #<%= index + 1%></p>
<h3><%= link_to post.title, user_post_path(post.user, post) %>
</h3>
<p>Comments: <%+ post.comments.length %></p>
<p>Likes: <%+ post.likes.length %></p>
</li>
<% if post.comments.length === 0 %>
<li>There are no comments</li>
<% else %>
<li>These are current Comments.</li>
<ul class='post-container'>
<% post.recent_comments.each do |comment| %>
<li><%= comment.text %></li>
<% end %>
</ul>

<% end %>
<% end %>

 <button>Pagination<button>
</div>

app/views/posts/new.html.erb
<h1>Hello i am new page</h1>
<section class="create-form">
  <h1>Create a post</h1>
  <%= form_with model: @post, url: user_posts_path(current_user), method: :post, local: true, scope: :post do |form| %>
    <li>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </li>

    <li>
      <%= form.label :text %>
      <%= form.text_field :text %>
    </li>

    <%= form.submit "Add Post" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<section id='post-container'>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<div id='post-header'>
<p>Post # <%= @post.id %> by <%= @user.name%></p>
<p>Post # <%= @post.title %> by <%= @user.name%></p>
<p>Comments: <%= @post.commentscounter %>, Likes: <%= @post.likescounter %></p>
</div>
<p class='post-body'><%= @post.text %></p>
<% if @post.comments.length === 0 %>
<p>There are no comments</p>
<% else %>
<p>These are the current Comments.</p>
<ul>
<% @post.recent_comments.each do |comment| %>
<li><%= comment.text %> 
<li><%= comment.text %> by <%= @user.name %>
<%= form_with url: "/users/#{@post.user.id}/posts/#{@post.id}/likes" do |f| %>
      <%= f.submit 'Like' %>
    <%end%></li>
 
<% end %>
</ul>
<% end %>
</section>

app/views/users/index.html.erb
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% if @users.blank? %>
<p>There are no users</p>
<% else %>
<p>These are current Users.</p>

<ul>
<% @users.each do |u| %>
<li>
 <img src="<%= u.photo %>" alt="image">
 <h2><%= link_to u.name, {:action => 'show', :id => u.id}  %></h2>
 <p>Number of posts: <%= u.posts.length %> </p>
</li>
<% end %>
</ul>
<% end %>

app/views/users/show.html.erb
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<section id='user-container'>
<img src="<%= @user.photo %>" alt="image">
<h1><%= @user.name%></h1>
<p>Number of post: <%= @user.posts.length%></p>
</section>
<p id='user-bio'><%= @user.bio %></>
<div class='post-container'>
<% @posts.each_with_index do |post,index| %>
<li>
<p>Post #<%= index + 1%></p>
 <h3><%= link_to post.title, controller: "posts", action: "show", user_id: @user.id, post_id: post.id %></h3>
<p>Comments: <%= post.commentscounter %></p>
<p>Likes: <%= post.likescounter %></p>
</li>
<% end %>
<li>
<button><%= link_to 'See all the posts', controller: 'posts', action: 'index', user_id: @user.id %></button>
</li>
<p>Recent posts:</p>
</div>